# Generated by Django 5.2.8 on 2025-11-07 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=0)),
                (
                    "currency_symbol",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plan", models.CharField(max_length=100)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
