# Generated by Django 6.0.1 on 2026-03-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
