# Generated by Django 6.0.1 on 2026-03-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_task_assigned_to_task_created_by_task_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="api.project",
            ),
        ),
    ]
