# Generated by Django 6.0.1 on 2026-03-26 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_projectmembership_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("member", "Member")],
                default="member",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ProjectInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(default="member", max_length=10)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="api.project",
                    ),
                ),
            ],
        ),
    ]
